[package]
name = "etfmxr"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
egui-file-dialog = "0.7.0"
anyhow.workspace = true
cpal.workspace = true
env_logger.workspace = true
log.workspace = true
clap.workspace = true
tfmxr.path = "../../"
egui-inspect.workspace = true
