[package]
name = "etfmxr"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui-file-dialog = "0.10.0"
anyhow.workspace = true
cpal.workspace = true
env_logger.workspace = true
log.workspace = true
clap.workspace = true
tfmxr.path = "../../"
